---
- hosts: localhost
  connection: local

  tasks:
  - name: start an instances with a public IP address
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "mumbaiKey"
      vpc_subnet_id: subnet-08aaefe8716bd1d92
      instance_type: t2.micro
      region: ap-south-1
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      security_group: jenkins-SG
      network:
       assign_public_ip: true
      image_id: "{{ item.image }}"
    loop:
      - {image: "ami-068e0f1a600cd311c", name: manage-node_1} 
      - {image: "ami-0ad21ae1d0696ad58", name: manage-node_2}
      - {image: "ami-0ad21ae1d0696ad58", name: manage-node_3}