pipeline {
    agent any

    environment {
        repo_name = "https://github.com/rahil05mathur/ansible-CI-CD"
        branch = "main"
        ansible_playbook_path = "ansible-new-project"
        ssh_cred = "044c7c9f-fd49-46ac-b9d3-39033f44d4ae"
        vault_password_file = "~/vault.pass"
    }


    stages {

        stage('Checkout') {
            steps {
                git branch: branch, url: repo_name
            }
        }

        stage ('Create EC2 Instances') {
            steps {
                sshagent(['ssh_cred']) {
                    sh """
                    ansible-playbook ${ansible_playbook_path}/ec2_create.yml -i ${ansible_playbook_path}/inventory.ini --vault-password-file ${vault_password_file}
                    """
                }
            }
        }

    stage ('setup ansible environment') {
        steps {
            script {
                    sh """
                    # install python dependencies
                    pip install -r ${ansible_playbook_path}/requirements.txt

                    # Install Ansible Galaxy Collections
                    ansible-galaxy collection install amazon.aws
                    """
                }
            }
        }

        stage ('mv vault file to jenkins home directoy') {
            steps {
                script {
                    sh """
                    chmod 400 ~/vault.pass
                    """
                }
            }
        }

        stage('Stop EC2 Instances') {
            steps {
                sshagent([ssh_cred]) {
                    sh """
                    ansible-playbook ${ansible_playbook_path}/ec2_stop.yml -i ${ansible_playbook_path}/inventory.ini --vault-password-file ${vault_password_file}
                    """
                }
            }
        }

    }
}
